[project]
name = "inspect-stockfish"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "inspect-ai>=0.3.74",
    "openai>=1.66.3",
    "pandas>=2.2.3",
    "ruff>=0.11.0",
    "stockfish>=3.28.0",
]
